import Head from 'next/head';
import Header from '../partials/header';
import HomePage from './home.page';
import Image from 'next/image';
import Script from 'next/script'

export default function Home() {

    return (
        <div className="h-screen bg-[url('/images/said-ait-driss-back1.jpg')] bg-no-repeat bg-cover bg-center">
            <Head>
                <Script
                    async
                    src={`https://www.googletagmanager.com/gtag/js?id=G-BELHMW8GX8`}
                />
                <Script
                    dangerouslySetInnerHTML={{
                        __html: `
                window.dataLayer = window.dataLayer || [];
                function gtag(){dataLayer.push(arguments);}
                gtag('js', new Date());

                gtag('config', 'G-BELHMW8GX8', {
                  page_path: window.location.pathname,
                });
              `,
                    }}
                />
                <title>Said Ait Driss</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header></Header>
            <HomePage></HomePage>
            <button
                title="know more about me"
                className="absolute bottom-0 left-0 right-0 mx-auto text-white font-bold py-2 px-4 animate-bounce duration-300">
                <Image
                    src={'/images/svg/arrow-down.svg'}
                    width={40}
                    height={60}
                    className="shadow hover:scale-125"
                />
            </button>
        </div>
    );
}
